---
es_instance_name: "{{ cluster_name }}_{{ node_name }}"
es_version: 5.6.0
es_use_repository: false

es_api_basic_auth_username: admin
es_api_basic_auth_password: admin

es_home: "/data/elasticsearch-{{ es_version }}"
es_conf_dir: "{{ es_home }}/config"
es_data_dirs: "{{ es_home }}/data"
es_log_dir: "{{ es_home }}/logs"