---
es_config:
  node.master: true
  node.data: false
  http.cors.enabled: true
  http.cors.allow-origin: "*"
  discovery.zen.fd.ping_interval: 10s
  discovery.zen.fd.ping_timeout: 120s
  discovery.zen.fd.ping_retries: 6